"""End-to-end regression tests for the Round-4 expanded test corpus.

These tests cover the three NEW fixtures generated by
`tests/fixtures/build_corpus.py`:

    - logistics_routing_synth.xlsm    -> domain `logistics-routing`
    - inventory_supply_synth.xlsm     -> domain `inventory-supply-chain`
    - minimal_no_vba.xlsm             -> domain `unknown` (degradation)

For each fixture we assert:
    1. The audit completes (rc == 0).
    2. Idempotency holds (two runs yield byte-identical md + json).
    3. The detected domain matches expectation.
    4. The complexity score sits inside an expected ±5 band.
    5. A specific expected pillar (or the absence of pillars) is present.
    6. A specific expected workflow signal (button vs. graceful-empty).
    7. All H2 sections that should be there ARE there.

The number ranges below are documented in `docs/test-corpus.md` and serve as
the canonical regression baseline going forward. If any of these starts
diverging, either the audit logic changed (intentionally — bump the range)
or the corpus changed (un-intended — investigate before tweaking the test).
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from tier1_audit.cli import main as cli_main


REPO_ROOT = Path(__file__).resolve().parents[1]
FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"

LOGISTICS_FIXTURE = FIXTURES_DIR / "logistics_routing_synth.xlsm"
INVENTORY_FIXTURE = FIXTURES_DIR / "inventory_supply_synth.xlsm"
MINIMAL_FIXTURE   = FIXTURES_DIR / "minimal_no_vba.xlsm"


def _run_audit(input_path: Path, out_dir: Path):
    out_dir.mkdir(parents=True, exist_ok=True)
    rc = cli_main([str(input_path), "--out-dir", str(out_dir)])
    md = (out_dir / "audit.md").read_text(encoding="utf-8")
    js_text = (out_dir / "audit.json").read_text(encoding="utf-8")
    return rc, md, js_text


def _load_json(out_dir: Path) -> dict:
    return json.loads((out_dir / "audit.json").read_text(encoding="utf-8"))


# Required H2 sections that must always be present, regardless of fixture.
# Note: "Domain-Specific Findings" is intentionally CONDITIONAL — it only
# renders when at least one domain template matches with high/medium
# confidence. We assert that separately per-fixture.
_REQUIRED_H2_SECTIONS = (
    "## Executive Summary",
    "## Table of Contents",
    "## Workflow Guide",
    "## Data Flow Story",
    "## Top Impact Findings",
    "## VBA Module Walkthrough",
    "## Reference Appendix",
    "## Glossary",
    "## Methodology",
)


def _assert_required_sections(md: str, fixture_name: str):
    for sec in _REQUIRED_H2_SECTIONS:
        assert sec in md, f"{fixture_name}: missing required section {sec!r}"


# ============================================================================
# Logistics-Routing Fixture
# ============================================================================

def test_logistics_audit_completes(tmp_path: Path):
    if not LOGISTICS_FIXTURE.exists():
        pytest.skip("logistics fixture not built — run build_corpus.py")
    rc, md, _ = _run_audit(LOGISTICS_FIXTURE, tmp_path / "out")
    assert rc == 0
    assert md.startswith("# Audit report")
    _assert_required_sections(md, "logistics_routing_synth")


def test_logistics_idempotent(tmp_path: Path):
    if not LOGISTICS_FIXTURE.exists():
        pytest.skip("logistics fixture not built")
    out1 = tmp_path / "run1"
    out2 = tmp_path / "run2"
    rc1, md1, js1 = _run_audit(LOGISTICS_FIXTURE, out1)
    rc2, md2, js2 = _run_audit(LOGISTICS_FIXTURE, out2)
    assert rc1 == 0 and rc2 == 0
    assert md1 == md2, "logistics audit.md should be byte-identical"
    assert js1 == js2, "logistics audit.json should be byte-identical"


def test_logistics_domain_detected(tmp_path: Path):
    if not LOGISTICS_FIXTURE.exists():
        pytest.skip("logistics fixture not built")
    _run_audit(LOGISTICS_FIXTURE, tmp_path / "out")
    j = _load_json(tmp_path / "out")
    dh = j.get("domain_hint") or {}
    assert dh.get("domain") == "logistics-routing", \
        f"expected logistics-routing, got {dh.get('domain')}"
    assert dh.get("confidence") in {"high", "medium"}, \
        f"expected high/medium confidence, got {dh.get('confidence')}"
    # Template-level: logistics-routing template should fire at high/medium
    matches = j.get("domain_template_matches") or []
    keys_conf = {m["template_key"]: m["confidence"] for m in matches}
    assert "logistics-routing" in keys_conf, \
        f"logistics template should match, got {list(keys_conf)}"
    assert keys_conf["logistics-routing"] in {"high", "medium"}, \
        f"logistics template confidence {keys_conf['logistics-routing']!r}"


def test_logistics_complexity_in_range(tmp_path: Path):
    if not LOGISTICS_FIXTURE.exists():
        pytest.skip("logistics fixture not built")
    _run_audit(LOGISTICS_FIXTURE, tmp_path / "out")
    j = _load_json(tmp_path / "out")
    score = j["complexity"]["total"]
    assert 63 <= score <= 73, f"logistics complexity {score} outside [63,73]"


def test_logistics_expected_pillar_routes(tmp_path: Path):
    """The Routes sheet's RouteID column (A2..A31) is a pillar:
    each cell is referenced by 1 SUMIFS in Routes!F* + ~99 INDEX/MATCH
    in Shipments!E*. Fan-in >= 20 is the threshold."""
    if not LOGISTICS_FIXTURE.exists():
        pytest.skip("logistics fixture not built")
    _run_audit(LOGISTICS_FIXTURE, tmp_path / "out")
    j = _load_json(tmp_path / "out")
    pillars = j.get("pillars") or []
    assert pillars, "logistics fixture should have at least 1 pillar"
    # At least one pillar should be a Routes!A column-block group
    routes_pillar = next(
        (p for p in pillars
         if p.get("pillar_kind") == "column-block" and "Routes!A" in p["location"]),
        None,
    )
    assert routes_pillar is not None, \
        f"expected a Routes!A column-block pillar; got: {[p['location'] for p in pillars]}"
    assert routes_pillar["fan_in"] >= 20


def test_logistics_button_detected(tmp_path: Path):
    """A real form-control button bound to `[0]!Execute` is injected on
    the Routes sheet. The workflow detector should pick it up."""
    if not LOGISTICS_FIXTURE.exists():
        pytest.skip("logistics fixture not built")
    rc, md, _ = _run_audit(LOGISTICS_FIXTURE, tmp_path / "out")
    assert rc == 0
    j = _load_json(tmp_path / "out")
    wf = j.get("workflow") or {}
    btns = wf.get("buttons") or []
    assert len(btns) >= 1, f"logistics should have >= 1 button, got {btns}"
    # The button macro should match what we injected
    assert any("Execute" in b.get("macro", "") for b in btns), \
        f"expected an 'Execute' macro button, got: {btns}"
    # Workflow Guide should reference the button label
    assert "Run Routing Calculation" in md, \
        "Routes button label should appear in markdown"


# ============================================================================
# Inventory-Supply-Chain Fixture
# ============================================================================

def test_inventory_audit_completes(tmp_path: Path):
    if not INVENTORY_FIXTURE.exists():
        pytest.skip("inventory fixture not built — run build_corpus.py")
    rc, md, _ = _run_audit(INVENTORY_FIXTURE, tmp_path / "out")
    assert rc == 0
    assert md.startswith("# Audit report")
    _assert_required_sections(md, "inventory_supply_synth")


def test_inventory_idempotent(tmp_path: Path):
    if not INVENTORY_FIXTURE.exists():
        pytest.skip("inventory fixture not built")
    out1 = tmp_path / "run1"
    out2 = tmp_path / "run2"
    rc1, md1, js1 = _run_audit(INVENTORY_FIXTURE, out1)
    rc2, md2, js2 = _run_audit(INVENTORY_FIXTURE, out2)
    assert rc1 == 0 and rc2 == 0
    assert md1 == md2, "inventory audit.md should be byte-identical"
    assert js1 == js2, "inventory audit.json should be byte-identical"


def test_inventory_domain_detected(tmp_path: Path):
    if not INVENTORY_FIXTURE.exists():
        pytest.skip("inventory fixture not built")
    _run_audit(INVENTORY_FIXTURE, tmp_path / "out")
    j = _load_json(tmp_path / "out")
    dh = j.get("domain_hint") or {}
    assert dh.get("domain") == "inventory-supply-chain", \
        f"expected inventory-supply-chain, got {dh.get('domain')}"
    assert dh.get("confidence") in {"high", "medium"}, \
        f"expected high/medium confidence, got {dh.get('confidence')}"
    matches = j.get("domain_template_matches") or []
    keys_conf = {m["template_key"]: m["confidence"] for m in matches}
    assert "inventory-supply-chain" in keys_conf
    assert keys_conf["inventory-supply-chain"] in {"high", "medium"}


def test_inventory_complexity_in_range(tmp_path: Path):
    if not INVENTORY_FIXTURE.exists():
        pytest.skip("inventory fixture not built")
    _run_audit(INVENTORY_FIXTURE, tmp_path / "out")
    j = _load_json(tmp_path / "out")
    score = j["complexity"]["total"]
    assert 67 <= score <= 77, f"inventory complexity {score} outside [67,77]"


def test_inventory_expected_pillar_movements(tmp_path: Path):
    """The Movements!B column (SKU labels) is referenced by many SUMIFS
    aggregations in Reorder. Should produce a Movements!B column-block
    pillar at fan-in >= 20."""
    if not INVENTORY_FIXTURE.exists():
        pytest.skip("inventory fixture not built")
    _run_audit(INVENTORY_FIXTURE, tmp_path / "out")
    j = _load_json(tmp_path / "out")
    pillars = j.get("pillars") or []
    assert pillars, "inventory fixture should have at least 1 pillar"
    movements_pillar = next(
        (p for p in pillars
         if "Movements!" in p["location"] and p["fan_in"] >= 20),
        None,
    )
    assert movements_pillar is not None, \
        f"expected a Movements pillar; got: {[p['location'] for p in pillars]}"


def test_inventory_no_buttons(tmp_path: Path):
    """Inventory fixture inherits VBA from donor but has NO button bindings —
    workflow detector should report 'no buttons detected' gracefully."""
    if not INVENTORY_FIXTURE.exists():
        pytest.skip("inventory fixture not built")
    rc, md, _ = _run_audit(INVENTORY_FIXTURE, tmp_path / "out")
    assert rc == 0
    j = _load_json(tmp_path / "out")
    wf = j.get("workflow") or {}
    assert (wf.get("no_buttons_detected") is True
            or len(wf.get("buttons") or []) == 0), \
        "inventory should have no buttons"
    assert ("no user-callable buttons" in md.lower()
            or "formula-driven only" in md.lower()), \
        "inventory should report 'no buttons detected' gracefully"


# ============================================================================
# Minimal (no VBA) Fixture — degradation/robustness
# ============================================================================

def test_minimal_audit_completes(tmp_path: Path):
    if not MINIMAL_FIXTURE.exists():
        pytest.skip("minimal fixture not built — run build_corpus.py")
    rc, md, _ = _run_audit(MINIMAL_FIXTURE, tmp_path / "out")
    assert rc == 0, "minimal fixture audit should not crash"
    assert md.startswith("# Audit report")
    _assert_required_sections(md, "minimal_no_vba")


def test_minimal_idempotent(tmp_path: Path):
    if not MINIMAL_FIXTURE.exists():
        pytest.skip("minimal fixture not built")
    out1 = tmp_path / "run1"
    out2 = tmp_path / "run2"
    rc1, md1, js1 = _run_audit(MINIMAL_FIXTURE, out1)
    rc2, md2, js2 = _run_audit(MINIMAL_FIXTURE, out2)
    assert rc1 == 0 and rc2 == 0
    assert md1 == md2, "minimal audit.md should be byte-identical"
    assert js1 == js2, "minimal audit.json should be byte-identical"


def test_minimal_unknown_domain(tmp_path: Path):
    """Minimal fixture has no domain-relevant keywords; domain should be
    'unknown' with confidence 'none'."""
    if not MINIMAL_FIXTURE.exists():
        pytest.skip("minimal fixture not built")
    _run_audit(MINIMAL_FIXTURE, tmp_path / "out")
    j = _load_json(tmp_path / "out")
    dh = j.get("domain_hint") or {}
    assert dh.get("domain") == "unknown", \
        f"expected 'unknown' domain, got {dh.get('domain')}"
    assert dh.get("confidence") == "none", \
        f"expected 'none' confidence, got {dh.get('confidence')}"
    # No domain-specific findings section
    matches = j.get("domain_template_matches") or []
    high_med = [m for m in matches if m["confidence"] in {"high", "medium"}]
    assert not high_med, \
        f"minimal fixture should not match any template at high/medium, got {high_med}"


def test_minimal_complexity_in_range(tmp_path: Path):
    if not MINIMAL_FIXTURE.exists():
        pytest.skip("minimal fixture not built")
    _run_audit(MINIMAL_FIXTURE, tmp_path / "out")
    j = _load_json(tmp_path / "out")
    score = j["complexity"]["total"]
    # Minimal: 30 cells, 8 formulas, no VBA, no metadata.
    # Expected: low total but non-zero (smell density gets boosted by small N).
    assert 25 <= score <= 40, f"minimal complexity {score} outside [25,40]"


def test_minimal_no_vba_modules(tmp_path: Path):
    """Minimal fixture is a pure xlsm with no vbaProject.bin part.
    The audit should report 0 modules cleanly — not crash."""
    if not MINIMAL_FIXTURE.exists():
        pytest.skip("minimal fixture not built")
    _run_audit(MINIMAL_FIXTURE, tmp_path / "out")
    j = _load_json(tmp_path / "out")
    assert j["basic_stats"]["vba_module_count"] == 0
    assert j["basic_stats"]["vba_total_lines"] == 0
    # vba_classifications should be empty
    assert (j.get("vba_classifications") or []) == []
    # No Domain-Specific Findings section in markdown — graceful conditional.
    md = (tmp_path / "out" / "audit.md").read_text(encoding="utf-8")
    assert "## Domain-Specific Findings" not in md, \
        "minimal fixture should not render Domain-Specific Findings section"


def test_minimal_graceful_empty_workflow(tmp_path: Path):
    """No buttons + no event handlers → graceful narrative."""
    if not MINIMAL_FIXTURE.exists():
        pytest.skip("minimal fixture not built")
    _, md, _ = _run_audit(MINIMAL_FIXTURE, tmp_path / "out")
    assert ("no user-callable buttons" in md.lower()
            or "formula-driven only" in md.lower())
    # No Mermaid VBA diagram on a 0-module workbook (graceful empty)
    # but the section itself should still be present.
    assert "## VBA Module Walkthrough" in md


# ============================================================================
# Cross-fixture invariants — Round 4 regression baseline
# ============================================================================

NEW_FIXTURES = [
    ("logistics_routing_synth", LOGISTICS_FIXTURE, "logistics-routing"),
    ("inventory_supply_synth", INVENTORY_FIXTURE, "inventory-supply-chain"),
    ("minimal_no_vba",          MINIMAL_FIXTURE,   "unknown"),
]


@pytest.mark.parametrize("name,path,_expected_domain", NEW_FIXTURES)
def test_new_corpus_runs_clean(tmp_path: Path, name: str, path: Path, _expected_domain: str):
    if not path.exists():
        pytest.skip(f"{name} fixture not built — run build_corpus.py")
    rc, md, js = _run_audit(path, tmp_path / "out")
    assert rc == 0
    j = json.loads(js)
    assert j["meta"]["file_name"] == path.name
    # Always emits valid JSON with the structural fields the renderer expects
    for key in ("basic_stats", "complexity", "smells", "pillars",
                "anomalies", "vba_modules", "vba_classifications",
                "workflow", "vba_narratives", "domain_hint",
                "domain_template_matches", "methodology"):
        assert key in j, f"{name}: missing JSON key {key}"


@pytest.mark.parametrize("name,path,expected_domain", NEW_FIXTURES)
def test_new_corpus_domain_match(tmp_path: Path, name: str, path: Path, expected_domain: str):
    if not path.exists():
        pytest.skip(f"{name} fixture not built")
    _run_audit(path, tmp_path / "out")
    j = _load_json(tmp_path / "out")
    actual = (j.get("domain_hint") or {}).get("domain", "unknown")
    assert actual == expected_domain, \
        f"{name}: expected domain {expected_domain!r}, got {actual!r}"
